export type { Category } from '../../categories/types'

export interface Transaction {
  id: string
  concept: string
  amount: number
  date: string
  type: 'income' | 'expense'
  categoryId: string
  /** True when the transaction was auto-generated by a recurrence. */
  isRecurring?: boolean
  /** Id of the recurrence that generated this transaction. */
  recurringId?: string
  /** Owner user id. Missing on legacy/demo rows; defaults to the current user. */
  userId?: string
  /**
   * Group context this transaction belongs to (group-shared ledgers, HU-0.8).
   * Absent means the transaction is personal.
   */
  groupId?: string
}