import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import type { Locale } from '../lib/dates'
import { todayIso } from '../lib/dates'
import type { Budget } from '../features/budgeting/types'
import type { Category } from '../features/categories/types'
import type { RecurringTransaction, OccurrenceOverride } from '../features/recurring/types'
import { materializeDue } from '../features/recurring/services/recurrenceService'
import { PREDEFINED_CATEGORIES } from '../features/categories/data/predefined'
import {
  demoBudgets,
  demoCategories,
  demoInvestments,
  demoTransactions,
} from '../features/dashboard/data/demo'
import { loadPersistedState, savePersistedState } from '../lib/storageService'

export type { Category } from '../features/categories/types'

export interface Transaction {
  id: string
  concept: string
  amount: number
  date: string
  type: 'income' | 'expense'
  categoryId: string
  /** True when the transaction was auto-generated by a recurrence. */
  isRecurring?: boolean
  /** Id of the recurrence that generated this transaction. */
  recurringId?: string
}

export interface Investment {
  id: string
  name: string
  ticker?: string
  type: 'stocks' | 'funds' | 'crypto' | 'bonds' | 'other'
  purchaseDate: string
  quantity: number
  investedAmount: number
  currency: string
  currentValue?: number
}

export type UndoEntity =
  | { kind: 'transaction'; item: Transaction }
  | { kind: 'category'; item: Category }
  | { kind: 'investment'; item: Investment }
  | { kind: 'budget'; item: Budget }

interface Storage {
  locale: Locale
  transactions: Transaction[]
  categories: Category[]
  investments: Investment[]
  budgets: Budget[]
  recurrings: RecurringTransaction[]
}

export interface AppState {
  locale: Locale
  setLocale: (locale: Locale) => void
  store: Storage
  /**
   * True while persisted state is being hydrated at boot. While booting, the
   * app shell renders a skeleton screen instead of eager section content so
   * the user sees immediate feedback on first load.
   */
  isBooting: boolean
  /** When true, the last write to localStorage failed (e.g. quota). */
  storageError: boolean
  addTransaction: (t: Omit<Transaction, 'id'>) => void
  addCategory: (c: Omit<Category, 'id'>) => void
  updateCategory: (id: string, c: Partial<Omit<Category, 'id'>>) => void
  addInvestment: (i: Omit<Investment, 'id'>) => void
  addBudget: (b: Omit<Budget, 'id'>) => void
  updateBudget: (id: string, b: Omit<Budget, 'id'>) => void
  addRecurring: (r: Omit<RecurringTransaction, 'id'>) => void
  updateRecurring: (id: string, patch: Partial<RecurringTransaction>) => void
  removeRecurring: (id: string) => void
  /** Pause (false) or resume (true) a recurrence. */
  setRecurringActive: (id: string, isActive: boolean) => void
  /** Single-occurrence override for the scheduled occurrence on `date`. */
  setOccurrenceOverride: (id: string, date: string, override: OccurrenceOverride) => void
  remove: (entity: UndoEntity) => void
  restore: (entity: UndoEntity) => void
  /** Materializes due occurrences (idempotent). Returns generated count. */
  syncDue: () => number
  /** Replaces the store with the bundled demo dataset (explicit opt-in). */
  loadDemo: () => void
}

const AppStateContext = createContext<AppState | null>(null)

function now(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}`
}

/**
 * How long the app holds the boot skeleton while hydrating persisted state.
 * Real first-load latency comes from the storage read; a small floor keeps
 * the skeleton recognizable instead of a single-frame flash. Tests can lower
 * it (or pass `initialStore`) to stay deterministic.
 */
export const BOOT_DELAY_MS = 260

/**
 * Minimum delay for async demo-data loading so the spinner is perceptible.
 * Mirrors fetching a remote dataset; falls back to the bundled snapshot.
 */
export const DEMO_LOAD_DELAY_MS = 400

export function AppStateProvider({
  children,
  initialStore,
  seedDemo = false,
  bootDelayMs = BOOT_DELAY_MS,
}: {
  children: ReactNode
  initialStore?: Partial<Storage>
  /** When true (and no persisted state exists) the demo dataset is loaded. */
  seedDemo?: boolean
  /** How long the boot skeleton is shown while state hydrates. */
  bootDelayMs?: number
}) {
  // State starts at defaults; persisted values are applied asynchronously by
  // the boot effect below so the initial paint can show a skeleton.
  const [locale, setLocale] = useState<Locale>(initialStore?.locale ?? 'es')
  const [transactions, setTransactions] = useState<Transaction[]>(
    initialStore?.transactions ?? (seedDemo ? demoTransactions : []),
  )
  const [categories, setCategories] = useState<Category[]>(
    initialStore?.categories ?? PREDEFINED_CATEGORIES,
  )
  const [investments, setInvestments] = useState<Investment[]>(
    initialStore?.investments ?? (seedDemo ? demoInvestments : []),
  )
  const [budgets, setBudgets] = useState<Budget[]>(
    initialStore?.budgets ?? (seedDemo ? demoBudgets : []),
  )
  const [recurrings, setRecurrings] = useState<RecurringTransaction[]>(
    initialStore?.recurrings ?? [],
  )
  const [storageError, setStorageError] = useState(false)
  // Tests that inject `initialStore` get a synchronous store; otherwise the
  // provider boots asynchronously and the app shell shows the skeleton.
  const [isBooting, setIsBooting] = useState<boolean>(
    typeof initialStore === 'undefined',
  )

  // Boot hydration: reads the persisted snapshot after the first paint (so
  // the browser can render the skeleton) and swaps it into the store.
  useEffect(() => {
    if (typeof initialStore !== 'undefined') return
    let cancelled = false
    const timer = window.setTimeout(() => {
      const loaded = loadPersistedState()
      if (cancelled) return
      if (loaded !== null) {
        setLocale(loaded.locale)
        setTransactions(loaded.transactions)
        setCategories(loaded.categories)
        setInvestments(loaded.investments)
        setBudgets(loaded.budgets)
        setRecurrings(loaded.recurrings)
      }
      setIsBooting(false)
    }, bootDelayMs)
    return () => {
      cancelled = true
      window.clearTimeout(timer)
    }
  }, [initialStore, bootDelayMs])

  // Refs so `syncDue` can read the latest slices without re-creating the
  // callback and re-triggering consumers on every render.
  const transactionsRef = useRef(transactions)
  const recurringsRef = useRef(recurrings)

  // Update refs after render so syncDue always reads current values.
  useEffect(() => {
    transactionsRef.current = transactions
    recurringsRef.current = recurrings
  })

  // Persistence: any change to the store (or locale) is written to
  // localStorage. Write errors are surfaced via `storageError` instead of
  // crashing the UI. The effect is skipped while booting so a not-yet-
  // hydrated default store cannot overwrite the persisted snapshot.
  useEffect(() => {
    if (initialStore !== undefined || isBooting) return
    const error = savePersistedState({
      locale,
      transactions,
      categories,
      investments,
      budgets,
      recurrings,
    })
    // Persist on state change; reporting the write result is a side effect
    // of the same effect, so the setState here is intentional.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setStorageError(error !== null)
  }, [locale, transactions, categories, investments, budgets, recurrings, initialStore, isBooting])

  const syncDue = useMemo(
    () => (): number => {
      const { generated, nextExecutions } = materializeDue(
        recurringsRef.current,
        transactionsRef.current,
        todayIso(),
      )
      if (generated.length === 0) return 0
      if (generated.length > 0) {
        setTransactions((prev) => [
          ...prev,
          ...generated.map((g) => ({ ...g, id: now('tx') })),
        ])
      }
      setRecurrings((prev) =>
        prev.map((r) =>
          nextExecutions[r.id] !== undefined
            ? { ...r, nextExecution: nextExecutions[r.id] }
            : r,
        ),
      )
      return generated.length
    },
    [],
  )

  // Automation: materialize every due occurrence whenever the schedule
  // changes. Idempotent, so repeated runs are safe.
  useEffect(() => {
    syncDue()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recurrings]) // No transactions dep: generation is deduplicated by ledger state.

  const value: AppState = {
    locale,
    setLocale,
    storageError,
    isBooting,
    store: { locale, transactions, categories, investments, budgets, recurrings },
    addTransaction: (t) =>
      setTransactions((prev) => [...prev, { ...t, id: now('tx') }]),
    addCategory: (c) => setCategories((prev) => [...prev, { ...c, id: now('cat') }]),
    updateCategory: (id, c) =>
      setCategories((prev) =>
        prev.map((x) => (x.id === id ? { ...x, ...c } : x)),
      ),
    addInvestment: (i) =>
      setInvestments((prev) => [...prev, { ...i, id: now('inv') }]),
    addBudget: (b) => setBudgets((prev) => [...prev, { ...b, id: now('bg') }]),
    updateBudget: (id, b) =>
      setBudgets((prev) => prev.map((x) => (x.id === id ? { ...x, ...b } : x))),
    addRecurring: (r) =>
      setRecurrings((prev) => [...prev, { ...r, id: now('rec') }]),
    updateRecurring: (id, patch) =>
      setRecurrings((prev) =>
        prev.map((x) => (x.id === id ? { ...x, ...patch } : x)),
      ),
    removeRecurring: (id) =>
      setRecurrings((prev) => prev.filter((x) => x.id !== id)),
    setRecurringActive: (id, isActive) =>
      setRecurrings((prev) =>
        prev.map((x) => (x.id === id ? { ...x, isActive } : x)),
      ),
    setOccurrenceOverride: (id, date, override) =>
      setRecurrings((prev) =>
        prev.map((x) => {
          if (x.id !== id) return x
          const exceptions = { ...(x.exceptions ?? {}), [date]: override }
          return { ...x, exceptions }
        }),
      ),
    remove: (entity) => {
      if (entity.kind === 'transaction') {
        setTransactions((prev) => prev.filter((x) => x.id !== entity.item.id))
      } else if (entity.kind === 'category') {
        setCategories((prev) => prev.filter((x) => x.id !== entity.item.id))
      } else if (entity.kind === 'investment') {
        setInvestments((prev) => prev.filter((x) => x.id !== entity.item.id))
      } else {
        setBudgets((prev) => prev.filter((x) => x.id !== entity.item.id))
      }
    },
    restore: (entity) => {
      if (entity.kind === 'transaction') {
        setTransactions((prev) => [...prev, entity.item])
      } else if (entity.kind === 'category') {
        setCategories((prev) => [...prev, entity.item])
      } else if (entity.kind === 'investment') {
        setInvestments((prev) => [...prev, entity.item])
      } else {
        setBudgets((prev) => [...prev, entity.item])
      }
    },
    loadDemo: () => {
      setTransactions(demoTransactions)
      setCategories(demoCategories)
      setBudgets(demoBudgets)
      setInvestments(demoInvestments)
    },
    syncDue,
  }

  return <AppStateContext.Provider value={value}>{children}</AppStateContext.Provider>
}

function useAppState(): AppState {
  const ctx = useContext(AppStateContext)
  if (!ctx) throw new Error('useAppState must be used within AppStateProvider')
  return ctx
}

export { useAppState }