import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import type { Locale } from '../lib/dates'
import { todayIso } from '../lib/dates'
import type { Budget } from '../features/budgeting/types'
import type { Category } from '../features/categories/types'
import type { RecurringTransaction, OccurrenceOverride } from '../features/recurring/types'
import { materializeDue, generationGuardFor } from '../features/recurring/services/recurrenceService'
import { readSessionUser } from '../features/auth/services/authService'
import { loadGroupSnapshot } from '../features/groups/services/groupStore'
import { recordGroupActivity } from '../features/groups/services/groupActivity'
import { PREDEFINED_CATEGORIES } from '../features/categories/data/predefined'
import {
  demoBudgets,
  demoCategories,
  demoInvestments,
  demoTransactions,
} from '../features/dashboard/data/demo'
import { loadPersistedState, savePersistedState } from '../lib/storageService'

export type { Category } from '../features/categories/types'
import type { ExpenseSplit, Settlement } from '../features/splits/types'

export interface Transaction {
  id: string
  concept: string
  amount: number
  date: string
  type: 'income' | 'expense'
  categoryId: string
  /** True when the transaction was auto-generated by a recurrence. */
  isRecurring?: boolean
  /** Id of the recurrence that generated this transaction. */
  recurringId?: string
  /** Group context this transaction belongs to (group-shared rules, HU-0.8). */
  groupId?: string
  /** Owner user id; absent on legacy/demo rows (the viewer owns them). */
  userId?: string
}

export interface Investment {
  id: string
  name: string
  ticker?: string
  type: 'stocks' | 'funds' | 'crypto' | 'bonds' | 'other'
  purchaseDate: string
  quantity: number
  investedAmount: number
  currency: string
  currentValue?: number
  gainLoss?: number
  /** Id of the group this investment belongs to (undefined = personal). */
  groupId?: string
  /** Id of the user who created the investment. */
  createdBy?: string
}

export interface InvestmentOwnership {
  investmentId: string
  userId: string
  /** Percentage of the group asset owned by this member (sum 100). */
  percentage: number
}

export type UndoEntity =
  | { kind: 'transaction'; item: Transaction; split?: ExpenseSplit }
  | { kind: 'category'; item: Category }
  | { kind: 'investment'; item: Investment; ownership?: InvestmentOwnership[] }
  | { kind: 'budget'; item: Budget }
  | { kind: 'settlement'; item: Settlement }

interface Storage {
  locale: Locale
  transactions: Transaction[]
  categories: Category[]
  investments: Investment[]
  investmentOwnerships: InvestmentOwnership[]
  budgets: Budget[]
  recurrings: RecurringTransaction[]
  /** Active budget context group id (null/absent = personal view, HU-0.8). */
  budgetGroupId: string | null
  /** Group expense splits (HU-0.7): one per shared transaction. */
  expenseSplits: ExpenseSplit[]
  /** Recorded member-to-member payments (HU-0.7), append-only history. */
  settlements: Settlement[]
}

export interface AppState {
  locale: Locale
  setLocale: (locale: Locale) => void
  store: Storage
  /**
   * Selects the budget context: personal (null) or a group (its id).
   * Budgets and the dashboard budget snapshot filter automatically (HU-0.8).
   */
  setBudgetGroupId: (groupId: string | null) => void
  /**
   * True while persisted state is being hydrated at boot. While booting, the
   * app shell renders a skeleton screen instead of eager section content so
   * the user sees immediate feedback on first load.
   */
  isBooting: boolean
  /** When true, the last write to localStorage failed (e.g. quota). */
  storageError: boolean
  addTransaction: (
    t: Omit<Transaction, 'id'>,
    split?: Omit<ExpenseSplit, 'transactionId'>,
  ) => void
  /** Reassign or edit an existing transaction (HU-0.6, MYF-22). */
  updateTransaction: (id: string, patch: Partial<Omit<Transaction, 'id'>>) => void
  /** Create or replace the split of an existing group transaction. */
  setTransactionSplit: (transactionId: string, split: ExpenseSplit | null) => void
  addSettlement: (s: Omit<Settlement, 'id' | 'createdAt'>) => void
  removeSettlement: (id: string) => void
  /**
   * Drops every financial row scoped to `groupId` (transactions, splits,
   * settlements, investments, budgets, recurring). Used by the group
   * dissolution flow (HU-0.12) after the group snapshot itself is removed.
   */
  removeGroupData: (groupId: string) => void
  addCategory: (c: Omit<Category, 'id'>) => void
  updateCategory: (id: string, c: Partial<Omit<Category, 'id'>>) => void
  addInvestment: (i: Omit<Investment, 'id'>, ownerships?: InvestmentOwnership[]) => void
  updateInvestment: (id: string, patch: Partial<Omit<Investment, 'id'>>) => void
  setInvestmentOwnerships: (investmentId: string, ownerships: InvestmentOwnership[]) => void
  addBudget: (b: Omit<Budget, 'id'>) => void
  updateBudget: (id: string, b: Omit<Budget, 'id'>) => void
  addRecurring: (r: Omit<RecurringTransaction, 'id'>) => void
  updateRecurring: (id: string, patch: Partial<RecurringTransaction>) => void
  removeRecurring: (id: string) => void
  /** Pause (false) or resume (true) a recurrence. */
  setRecurringActive: (id: string, isActive: boolean) => void
  /** Single-occurrence override for the scheduled occurrence on `date`. */
  setOccurrenceOverride: (id: string, date: string, override: OccurrenceOverride) => void
  remove: (entity: UndoEntity) => void
  restore: (entity: UndoEntity) => void
  /** Materializes due occurrences (idempotent). Returns generated count. */
  syncDue: () => number
  /** Replaces the store with the bundled demo dataset (explicit opt-in). */
  loadDemo: () => void
}

const AppStateContext = createContext<AppState | null>(null)

function now(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}`
}

/**
 * How long the app holds the boot skeleton while hydrating persisted state.
 * Real first-load latency comes from the storage read; a small floor keeps
 * the skeleton recognizable instead of a single-frame flash. Tests can lower
 * it (or pass `initialStore`) to stay deterministic.
 */
export const BOOT_DELAY_MS = 260

/**
 * Minimum delay for async demo-data loading so the spinner is perceptible.
 * Mirrors fetching a remote dataset; falls back to the bundled snapshot.
 */
export const DEMO_LOAD_DELAY_MS = 400

export function AppStateProvider({
  children,
  initialStore,
  seedDemo = false,
  bootDelayMs = BOOT_DELAY_MS,
}: {
  children: ReactNode
  initialStore?: Partial<Storage>
  /** When true (and no persisted state exists) the demo dataset is loaded. */
  seedDemo?: boolean
  /** How long the boot skeleton is shown while state hydrates. */
  bootDelayMs?: number
}) {
  // State starts at defaults; persisted values are applied asynchronously by
  // the boot effect below so the initial paint can show a skeleton.
  const [locale, setLocale] = useState<Locale>(initialStore?.locale ?? 'es')
  const [transactions, setTransactions] = useState<Transaction[]>(
    initialStore?.transactions ?? (seedDemo ? demoTransactions : []),
  )
  const [categories, setCategories] = useState<Category[]>(
    initialStore?.categories ?? PREDEFINED_CATEGORIES,
  )
  const [investments, setInvestments] = useState<Investment[]>(
    initialStore?.investments ?? (seedDemo ? demoInvestments : []),
  )
  const [investmentOwnerships, setInvestmentOwnerships] = useState<InvestmentOwnership[]>(
    initialStore?.investmentOwnerships ?? [],
  )
  const [budgets, setBudgets] = useState<Budget[]>(
    initialStore?.budgets ?? (seedDemo ? demoBudgets : []),
  )
  const [recurrings, setRecurrings] = useState<RecurringTransaction[]>(
    initialStore?.recurrings ?? [],
  )
  const [budgetGroupId, setBudgetGroupId] = useState<string | null>(
    initialStore?.budgetGroupId ?? null,
  )
  const [expenseSplits, setExpenseSplits] = useState<ExpenseSplit[]>(
    initialStore?.expenseSplits ?? [],
  )
  const [settlements, setSettlements] = useState<Settlement[]>(
    initialStore?.settlements ?? [],
  )
  const [storageError, setStorageError] = useState(false)
  // Tests that inject `initialStore` get a synchronous store; otherwise the
  // provider boots asynchronously and the app shell shows the skeleton.
  const [isBooting, setIsBooting] = useState<boolean>(
    typeof initialStore === 'undefined',
  )

  // Boot hydration: reads the persisted snapshot after the first paint (so
  // the browser can render the skeleton) and swaps it into the store.
  useEffect(() => {
    if (typeof initialStore !== 'undefined') return
    let cancelled = false
    const timer = window.setTimeout(() => {
      const loaded = loadPersistedState()
      if (cancelled) return
      if (loaded !== null) {
        setLocale(loaded.locale)
        setTransactions(loaded.transactions)
        setCategories(loaded.categories)
        setInvestments(loaded.investments)
        setInvestmentOwnerships(loaded.investmentOwnerships ?? [])
        setBudgets(loaded.budgets)
        setRecurrings(loaded.recurrings)
        setBudgetGroupId(loaded.budgetGroupId ?? null)
        setExpenseSplits(loaded.expenseSplits ?? [])
        setSettlements(loaded.settlements ?? [])
      }
      setIsBooting(false)
    }, bootDelayMs)
    return () => {
      cancelled = true
      window.clearTimeout(timer)
    }
  }, [initialStore, bootDelayMs])

  // Refs so `syncDue` can read the latest slices without re-creating the
  // callback and re-triggering consumers on every render.
  const transactionsRef = useRef(transactions)
  const recurringsRef = useRef(recurrings)

  // Update refs after render so syncDue always reads current values.
  useEffect(() => {
    transactionsRef.current = transactions
    recurringsRef.current = recurrings
  })

  // Persistence: any change to the store (or locale) is written to
  // localStorage. Write errors are surfaced via `storageError` instead of
  // crashing the UI. The effect is skipped while booting so a not-yet-
  // hydrated default store cannot overwrite the persisted snapshot.
  useEffect(() => {
    if (initialStore !== undefined || isBooting) return
    const error = savePersistedState({
      locale,
      transactions,
      categories,
      investments,
      investmentOwnerships,
      budgets,
      recurrings,
      budgetGroupId,
      expenseSplits,
      settlements,
    })
    // Persist on state change; reporting the write result is a side effect
    // of the same effect, so the setState here is intentional.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setStorageError(error !== null)
  }, [locale, transactions, categories, investments, investmentOwnerships, budgets, recurrings, budgetGroupId, expenseSplits, settlements, initialStore, isBooting])

  const syncDue = useMemo(
    () => (): number => {
      // Group rules (HU-0.8) only materialize while their creator keeps
      // `data.edit` in the group; the permission guard reads the persisted
      // session + group snapshot, exactly like any service would.
      const user = readSessionUser()
      const snapshot = loadGroupSnapshot()
      const { generated, nextExecutions } = materializeDue(
        recurringsRef.current,
        transactionsRef.current,
        todayIso(),
        { canGenerate: generationGuardFor(snapshot, user?.id ?? '') },
      )
      if (generated.length === 0) return 0
      if (generated.length > 0) {
        setTransactions((prev) => [
          ...prev,
          ...generated.map((g) => ({ ...g, id: now('tx') })),
        ])
      }
      setRecurrings((prev) =>
        prev.map((r) =>
          nextExecutions[r.id] !== undefined
            ? { ...r, nextExecution: nextExecutions[r.id] }
            : r,
        ),
      )
      return generated.length
    },
    [],
  )

  // Automation: materialize every due occurrence whenever the schedule
  // changes. Idempotent, so repeated runs are safe.
  useEffect(() => {
    syncDue()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recurrings]) // No transactions dep: generation is deduplicated by ledger state.

  const value: AppState = {
    locale,
    setLocale,
    storageError,
    isBooting,
    store: {
      locale,
      transactions,
      categories,
      investments,
      investmentOwnerships,
      budgets,
      recurrings,
      budgetGroupId,
      expenseSplits,
      settlements,
    },
    setBudgetGroupId: (groupId) => setBudgetGroupId(groupId),
    addTransaction: (t, split) => {
      // Stamp the owner so personal budgets only count own spending and group
      // budgets can break down consumption per member (HU-0.8).
      const owner = readSessionUser()?.id
      const id = now('tx')
      const stamped: Transaction = {
        ...t,
        id,
        userId: t.userId === undefined ? (owner ?? undefined) : t.userId,
      }
      setTransactions((prev) => [...prev, stamped])
      if (split) {
        setExpenseSplits((prev) => [
          ...prev.filter((s) => s.transactionId !== id),
          { ...split, transactionId: id },
        ])
      }
      if (t.groupId && owner) {
        recordGroupActivity({
          groupId: t.groupId,
          userId: owner,
          action: 'transaction_added',
          details: { concept: t.concept, amount: t.amount, type: t.type },
        })
        if (split) {
          recordGroupActivity({
            groupId: t.groupId,
            userId: owner,
            action: 'split_set',
            details: {
              concept: t.concept,
              count: split.shares.length,
              method: split.method,
            },
          })
        }
      }
    },
    updateTransaction: (id, patch) =>
      setTransactions((prev) =>
        prev.map((x) => (x.id === id ? { ...x, ...patch } : x)),
      ),
    setTransactionSplit: (transactionId, split) => {
      const previous = transactionsRef.current.find((x) => x.id === transactionId)
      setExpenseSplits((prev) =>
        split === null
          ? prev.filter((s) => s.transactionId !== transactionId)
          : [
              ...prev.filter((s) => s.transactionId !== transactionId),
              { ...split, transactionId },
            ],
      )
      const owner = readSessionUser()?.id
      if (split && previous?.groupId && owner) {
        recordGroupActivity({
          groupId: previous.groupId,
          userId: owner,
          action: 'split_set',
          details: { concept: previous.concept, count: split.shares.length },
        })
      }
    },
    addSettlement: (s) => {
      setSettlements((prev) => [
        { ...s, id: now('set'), createdAt: new Date().toISOString() },
        ...prev,
      ])
      const owner = readSessionUser()?.id
      if (owner) {
        recordGroupActivity({
          groupId: s.groupId,
          userId: owner,
          action: 'settlement_added',
          details: {
            amount: s.amount,
            fromUserId: s.fromUserId,
            toUserId: s.toUserId,
            recipientId: s.toUserId,
          },
        })
      }
    },
    removeSettlement: (id) => {
      const target = settlements.find((s) => s.id === id)
      setSettlements((prev) => prev.filter((s) => s.id !== id))
      const owner = readSessionUser()?.id
      if (target && owner) {
        recordGroupActivity({
          groupId: target.groupId,
          userId: owner,
          action: 'settlement_removed',
          details: { amount: target.amount },
        })
      }
    },
    addCategory: (c) => setCategories((prev) => [...prev, { ...c, id: now('cat') }]),
    updateCategory: (id, c) =>
      setCategories((prev) =>
        prev.map((x) => (x.id === id ? { ...x, ...c } : x)),
      ),
    addInvestment: (i, ownerships) => {
      const id = now('inv')
      setInvestments((prev) => [...prev, { ...i, id }])
      if (ownerships && ownerships.length > 0) {
        setInvestmentOwnerships((prev) => [
          ...prev.filter((o) => o.investmentId !== id),
          ...ownerships.map((o) => ({ ...o, investmentId: id })),
        ])
      }
      const owner = readSessionUser()?.id
      if (i.groupId && owner) {
        recordGroupActivity({
          groupId: i.groupId,
          userId: owner,
          action: 'investment_added',
          details: { name: i.name },
        })
      }
    },
    updateInvestment: (id, patch) => {
      const previous = investments.find((x) => x.id === id)
      setInvestments((prev) => prev.map((x) => (x.id === id ? { ...x, ...patch } : x)))
      if (previous && patch.groupId) {
        recordGroupActivity({
          groupId: patch.groupId,
          userId: readSessionUser()?.id ?? 'system',
          action: 'investment_updated',
          details: { name: patch.name ?? previous.name },
        })
      }
    },
    setInvestmentOwnerships: (investmentId, ownerships) =>
      setInvestmentOwnerships((prev) => [
        ...prev.filter((o) => o.investmentId !== investmentId),
        ...ownerships,
      ]),
    addBudget: (b) => {
      setBudgets((prev) => [...prev, { ...b, id: now('bg') }])
      if (b.groupId) {
        const category = categories.find((c) => c.id === b.categoryId)
        recordGroupActivity({
          groupId: b.groupId,
          userId: readSessionUser()?.id ?? 'system',
          action: 'budget_added',
          details: { category: category?.name ?? '', limit: b.limit },
        })
      }
    },
    updateBudget: (id, b) =>
      setBudgets((prev) => prev.map((x) => (x.id === id ? { ...x, ...b } : x))),
    addRecurring: (r) => {
      setRecurrings((prev) => [...prev, { ...r, id: now('rec') }])
      if (r.groupId) {
        recordGroupActivity({
          groupId: r.groupId,
          userId: readSessionUser()?.id ?? 'system',
          action: 'recurring_added',
          details: { concept: r.template.concept, amount: r.template.amount },
        })
      }
    },
    updateRecurring: (id, patch) =>
      setRecurrings((prev) =>
        prev.map((x) => (x.id === id ? { ...x, ...patch } : x)),
      ),
    removeRecurring: (id) => {
      const target = recurrings.find((x) => x.id === id)
      setRecurrings((prev) => prev.filter((x) => x.id !== id))
      if (target?.groupId) {
        recordGroupActivity({
          groupId: target.groupId,
          userId: readSessionUser()?.id ?? 'system',
          action: 'recurring_removed',
          details: { concept: target.template.concept },
        })
      }
    },
    setRecurringActive: (id, isActive) =>
      setRecurrings((prev) =>
        prev.map((x) => (x.id === id ? { ...x, isActive } : x)),
      ),
    setOccurrenceOverride: (id, date, override) =>
      setRecurrings((prev) =>
        prev.map((x) => {
          if (x.id !== id) return x
          const exceptions = { ...(x.exceptions ?? {}), [date]: override }
          return { ...x, exceptions }
        }),
      ),
    remove: (entity) => {
      const owner = readSessionUser()?.id
      if (entity.kind === 'transaction') {
        if (entity.item.groupId && owner) {
          recordGroupActivity({
            groupId: entity.item.groupId,
            userId: owner,
            action: 'transaction_removed',
            details: { concept: entity.item.concept, amount: entity.item.amount },
          })
        }
        setTransactions((prev) => prev.filter((x) => x.id !== entity.item.id))
        setExpenseSplits((prev) =>
          prev.filter((s) => s.transactionId !== entity.item.id),
        )
      } else if (entity.kind === 'category') {
        setCategories((prev) => prev.filter((x) => x.id !== entity.item.id))
      } else if (entity.kind === 'investment') {
        if (entity.item.groupId && owner) {
          recordGroupActivity({
            groupId: entity.item.groupId,
            userId: owner,
            action: 'investment_removed',
            details: { name: entity.item.name },
          })
        }
        setInvestments((prev) => prev.filter((x) => x.id !== entity.item.id))
        setInvestmentOwnerships((prev) =>
          prev.filter((o) => o.investmentId !== entity.item.id),
        )
} else if (entity.kind === 'settlement') {
        if (owner) {
          recordGroupActivity({
            groupId: entity.item.groupId,
            userId: owner,
            action: 'settlement_removed',
            details: { amount: entity.item.amount },
          })
        }
        setSettlements((prev) => prev.filter((s) => s.id !== entity.item.id))
      } else {
        if (entity.item.groupId && owner) {
          recordGroupActivity({
            groupId: entity.item.groupId,
            userId: owner,
            action: 'budget_removed',
            details: { category: '' },
          })
        }
        setBudgets((prev) => prev.filter((x) => x.id !== entity.item.id))
      }
    },
    restore: (entity) => {
      if (entity.kind === 'transaction') {
        const split = entity.split
        setTransactions((prev) => [...prev, entity.item])
        if (split) {
          setExpenseSplits((prev) => [...prev, split])
        }
      } else if (entity.kind === 'category') {
        setCategories((prev) => [...prev, entity.item])
      } else if (entity.kind === 'investment') {
        setInvestments((prev) => [...prev, entity.item])
        const ownership = entity.ownership ?? []
        setInvestmentOwnerships((prev) => [
          ...prev.filter((o) => o.investmentId !== entity.item.id),
          ...ownership,
        ])
      } else if (entity.kind === 'settlement') {
        setSettlements((prev) => [...prev, entity.item])
      } else {
        setBudgets((prev) => [...prev, entity.item])
      }
    },
    removeGroupData: (groupId) => {
      setTransactions((prev) => prev.filter((x) => x.groupId !== groupId))
      setExpenseSplits((prev) => prev.filter((s) => s.groupId !== groupId))
      setSettlements((prev) => prev.filter((s) => s.groupId !== groupId))
      setInvestments((prev) => prev.filter((x) => x.groupId !== groupId))
      setInvestmentOwnerships((prev) => [
        ...prev.filter((o) => {
          const inv = investments.find((i) => i.id === o.investmentId)
          return inv === undefined || inv.groupId !== groupId
        }),
      ])
      setBudgets((prev) => prev.filter((x) => x.groupId !== groupId))
      setRecurrings((prev) => prev.filter((x) => x.groupId !== groupId))
      if (budgetGroupId === groupId) setBudgetGroupId(null)
    },
    loadDemo: () => {
      setTransactions(demoTransactions)
      setCategories(demoCategories)
      setBudgets(demoBudgets)
      setInvestments(demoInvestments)
      setInvestmentOwnerships([])
      setExpenseSplits([])
      setSettlements([])
    },
    syncDue,
  }

  return <AppStateContext.Provider value={value}>{children}</AppStateContext.Provider>
}

function useAppState(): AppState {
  const ctx = useContext(AppStateContext)
  if (!ctx) throw new Error('useAppState must be used within AppStateProvider')
  return ctx
}

export { useAppState }